### ISSUE TITLE
Milestone #2 Documentation Attribution - Web Management Team 💻

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#102]
### Attribution
The purpose of this task is to present organized and detailed information of the achievements of the Website Management team towards the proper documentation and development on the **_Milestone 2 Documentation_**.

This will be updated to portray visibility in the documentation progression and results.

The assigned sections will be shown in further comments and will be discussed by Team Leaders alongside their Developers.

**Deadline: Fri, March 8 2024** 🚨

**Comment by smbv** [comment]
@Adriana-Isabel

**1.2.1 Current Situation:**
- Needs to focus more on describing the current situation without jumping directly into proposed solutions. Remove the sentence "We aim to fix this...".

**1.2.2 Needs:**
- Reframe the discussion to focus on actual needs rather than proposed solutions. Avoid talking about the system-to-be and instead identify the core needs of users.

@christianperez42

**1.2.3 Ideas:**
- Clarify how each idea addresses specific user needs rather than just mentioning features of the system. For example, elaborate on how a "user-friendly interface" satisfies a particular need.

@GiovanniMaysonet

**2.2.2 Personas:**
- Enhance the descriptions of personas to make them more vivid and representative of the target users. Ensure that each persona embodies a distinct set of goals, objectives, and characteristics to facilitate better understanding and decision-making within the project team.

@smbv

**1.3 & 1.5 Derived Goals:**
- Ensure that the derived goals are significantly different from the primary goals to avoid overlap. Revise the derived goals to provide a clear and distinct direction that complements the primary goals rather than replicating them.
