### ISSUE TITLE
Milestone #2 Documentation Attribution - Human Interfaces Team 🗿

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#104]
### Attribution
The purpose of this task is to present organized and detailed information of the achievements of the Human Interfaces team towards the proper documentation and development on the **Milestone 2 Documentation**.

This will be updated to portray visibility in the documentation progression and results.

The assigned sections will be shown in further comments and will be discussed by Team Leaders alongside their Developers.

**Deadline: Fri, March 8 2024** 🚨

**Comment by frances-sepulveda** [comment]
Derived goals (1.5). I created new derived goals according to the professor's comment on the documentation for M1.

**Comment by Javi510348** [comment]
Improvements and add information to Interface Requirements( 2.2.4)



The previous information from interface requirements has been modified following the recommendations from the feedback. Also, new requirements has been added including users and pets.

Interface Requirements:

-     The system must have a view in which it will allow management and/or shelter staff to update the availability of the pets.
-     The system should provide users a way to view and edit their profile information. Some of the information available for change could be the password, email, name, etc.
-     The system should provide a way in which shelter staff can register new pets to the website and to their specific shelter.
-     The system needs to allow users to bookmark pets in which they are interested.
-     The system needs a search bar, so that users can search for pets based on age, breed, personality, etc.
-     The system must provide a section in which new users can create an user account. The registration will consist of name, last name, email, username, password, etc.
-     The system must check for email validation by providing a unique user token that is generated randomly and sent by email to confirm the validation. This token will be provided by the user in a textbox in which it will confirm the validation of the email.
-     The system must allow management to handle the database with ease, so they can modify the necessary data within pets, shelters and/or users.
-     The system should allow users to fill out adoption forms if they wish to adopt a specific animal.
-     The system must track all of the status of the adoption forms filled out by users. The statuses could vary between denied, in-progress and approved.
-     The system must allow shelter staff to access the forms, so they can update the statuses of the forms based on the conclusions they reached about the potential adopter.
-     The system must track all of the adoptions completed within the website and share some successful stories within the website, so that users can see the success of the website.
-     The system needs to show the users the current status of their adoption and notify the final decision once it has been decided.
-     The system should have a notification section in which it will communicate to the user if there is a decision on a specific adoption form and/or if an animal that was bookmarked was adopted by another person.

If anyone has any recommendations or questions, pleas let me know.

**Comment by Saul-Caban-UPRM** [comment]
I expanded upon Concept Analysis for Milestone 2 based on the comments provided by the professor. Added secondary goals improving the whole idea of the project, added actions that the user can do as the end goal, and rephrased the last sentence in this section.

**Comment by RoBdIeL** [comment]
Domain Requirements 2.2.3. 

The added/modified section  outlines essential requirements, covering domain, interface, machine, and operational needs to ensure a user-friendly, efficient, and scalable platform. It addresses pet status tracking, user interaction, system capacity for updates, applicant identification, filtering options, accountability for pet care, privacy compliance, and overall system responsiveness. This is relevant for guiding development, ensuring the system meets user needs, regulatory standards, and can grow without performance loss.

**Comment by jhsanchez26** [comment]
Function Singatures 2.1.4

Updated/modified the Function Signatures section to include updates made since the first documentation.

**Comment by HectorSepul** [comment]
Terminology (2.1.2)

Improved the terminology section according to the professor's comments.

**Comment by ErickCruz4** [comment]
Domain Terminology 2.1.3

Updated/Modified the Domain Terminology section based on the comments provided by the professor.
