### ISSUE TITLE
Create profile page - Profile editing feature (will be split into other tasks for more features as progress is made)

### ISSUE THREAD

**Issue by ErickCruz4** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#107]
Creating a button that gives access to the profile settings and opens in a different page.

**Comment by ErickCruz4** [comment]
Added the profile section to the main page. When clicked, takes you to the user settings page, where the user is able to change their username, email and password. These changes were completed. Will be adding more features to this in a follow up. Future iterations could include additional customization options, such as profile picture uploads, notification preferences, or theme selections.

**Comment by RoBdIeL** [comment]
Changes involve both the front-end and the back-end, focusing on implementing functionality for users to view and update their profile settings. Here's a summary of the changes and the progress achieved:
 
settings.ejs: This page has been updated to include a form where users can input their new username, email, and password. Upon submission, a JavaScript fetch request is made to the /settings endpoint with the updated information.

index.js (Express Route Definitions):
A GET route for /settings to display the user's current settings. This route checks if the user is authenticated. If the user is authenticated, it fetches the user's settings and renders the settings.ejs view with this data. If not authenticated, it redirects the user to the login page.
The existing POST route for /settings to handle updates to user settings. This route uses the handleUpdateSettings function to process the update. 

I'm stuck in this part since I cannot verify my email with the verification code provided.

User Controller (handleUpdateSettings Function):

This function takes the updated user information from the request body and the user ID from the request's user object (assuming authentication middleware populates this). It then calls the DAO to update these settings in the database.
On successful update, it responds with a JSON object indicating success and the updated user information. On failure, it sends an error response.

Users DAO (updateSettings Function):

Implements the actual database query to update the user's username, email, and password (with the password being hashed before update) based on the provided user ID.
Returns the updated user's information, which the controller can then send back to the client.

Here are some pictures of the code.

![3-23ss1](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/99343992/a530c2f3-689c-4a1c-a92a-f0a49aa417f5)

![3-23ss2](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/99343992/b62362df-2798-47f5-9e85-35064573b359)

![3-23ss3](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/99343992/0a307c32-2878-4b0f-983f-dde43ea6a88f)
