### ISSUE TITLE
Pet Location Listing - Pet Listings

### ISSUE THREAD

**Issue by JohnSantiagoRuiz** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#21]
After all the pet breeds and species are filtered, we can add a feature where you select if you prefer a pet that's being put for adoption in a home, pet shelter, etc. We can also add a feature where you select your location so all the pets that are displayed are near your location. The farther you scroll down, the farther the pet is.

**Comment by evnd04** [comment]
I don't think this is a necessary feature for this project due to the implications of it being focused on the campus association that handles adoptions, most of them I imagine being local to Mayaguez unless I'm mistaken. And I'm pretty sure the pets are mostly handled by fosters on campus so the shelters/home identification I don't think would be that useful. However, I think this could change into being related to the foster's location in Mayaguez and adding their contact information for easy contact with the current foster.
